### PR TITLE
Divided Processor Classes into Files

### PR DESCRIPTION
**Pull request by t-sahin**
All 11 classes previously within 1 file were placed in individual files. Additionally, the original import section was for every class, however with individual files this section was individualized to the file. All classes by the "processor" class were deleted in the main file, processor.py, after being (for the most part) copy and pasted into another file.

### CODE REVIEW

**Comment by RainierBarrett** [comment]
We checked the changes but the vision code dies. There's no imports for the newly-divided files in the `controller.py` file, so it fails when it tries to create an instance of `BackgroundProcessor`. Here's the error: 

```
Traceback (most recent call last):
  File "c:\users\projectarco\arc-vision\arcvision\controller.py", line 81, in handle_start
    self.background_processor = BackgroundProcessor(self.cam)
NameError: name 'BackgroundProcessor' is not defined
,OpenCV Error: Assertion failed (!_src.empty()) in cv::pyrDown_, file C:\opencv_3.4\opencv-3.4.0\modules\imgproc\src\pyramids.cpp, line 858
Uncaught exception GET /stream/raw.mjpg?t=1527788294931 (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8077', method='GET', uri='/stream/raw.mjpg?t=1527788294931', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': '127.0.0.1:8077', 'Connection': 'keep-alive', 'X-Devtools-Request-Id': '11640.282', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Electron/1.7.5 Safari/537.36', 'Accept': 'image/webp,image/*,*/*;q=0.8', 'Referer': 'http://localhost:9080/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US'})
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\web.py", line 1511, in _execute
    result = yield result
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Program Files\Anaconda3\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "<string>", line 6, in _wrap_awaitable
  File "c:\users\projectarco\arc-vision\arcvision\server.py", line 51, in get
    frame = self.camera.get_decorated_frame(stream_name)
  File "c:\users\projectarco\arc-vision\arcvision\camera.py", line 190, in get_decorated_frame
    return cv2.pyrDown(self.decorated_frame)
cv2.error: C:\opencv_3.4\opencv-3.4.0\modules\imgproc\src\pyramids.cpp:858: error: (-215) !_src.empty() in function cv::pyrDown_

500 GET /stream/raw.mjpg?t=1527788294931 (127.0.0.1) 50.64ms
``` 

Need to change the `processor.py` file and any others that were previously using `from processor import *` to explicitly import all the class files. Possibly make them into one subpackage if it floats your boat.

**Comment by t-sahin** [comment]
I explicitly imported the class files used for the controller.py file. I must have overlooked the controller.py file because all other files have class files explicitly imported. Hopefully this resolves the issue.

**Comment by hgandhi2411** [comment]
Some imports are still failing. I believe you forgot to put a '.' while importing classes in tracker_processor.py and spatial_calibration_processor.py.

You have a duplication of one of the imports in the controller file.

The function object_id() in the processor.py file is not being used in the Processor class, it's being used in SpatialCalibrationProcessor and TrainingProcessor. So, that function can be moved to utils.py.

**Comment by hgandhi2411** [comment]
Looks good now!

**Pull request merged**
